### ISSUE TITLE
No title in the Students.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Edusera-Test#3]
The CSV table doesn't have a title. So someone please add it.

**Comment by ashishw1001** [comment]
I Want to take it.

**Comment by Pravallikasannapreddy** [comment]
HiI want to take this up

**Comment by praveenscience** [comment]
@Pravallikasannapreddy Accepted, I'll assign you the task.
@ashishw1001 Sorry man, it was for @Pravallikasannapreddy.
